name = "meccaway"
type = "javascript"
zone_id = "6f51700bac8ce9fee8597c3fe1245585"
account_id = "dd7ff4ee0a586c3497954beb8207ba0c"
compatibility_date = "2022-05-28"
route = { pattern = "*meccaway.com/*", zone_id = "6f51700bac8ce9fee8597c3fe1245585" }
workers_dev = true

[build]
command = "npm run build"
[build.upload]
format = "service-worker"

[site]
bucket = "./node_modules/@app/client/dist"
entry-point="."


[miniflare.globals]
IS_DEV=true
DEV_PORT=3000