name = "whenisthesunset"
type = "javascript"
zone_id = "a16c64615888c529b3a07504d818518d"
account_id = "dd7ff4ee0a586c3497954beb8207ba0c"
compatibility_date = "2022-05-28"
route = { pattern = "*whenisthesunset.com/*", zone_id = "a16c64615888c529b3a07504d818518d" }
workers_dev = true

[build]
command = "npm run build"
[build.upload]
format = "service-worker"

[site]
bucket = "./node_modules/@app/client/dist"
entry-point="."


[miniflare.globals]
IS_DEV=true
DEV_PORT=3000